spring:
    application:
        name: zhouzh3-bucket4j

    data:
        redis:
            #            host: ${redis.host}
            #            port: ${redis.port}
            host: localhost
            port: 6379
#            password: ${secret.redis.password:}  # 推荐从环境变量读取
            ssl:
                enabled: false
            lettuce:
                pool:
                    max-active: 8         # 最大连接数
                    max-idle: 4          # 最大空闲连接
                    min-idle: 1          # 最小空闲连接
                    max-wait: 2000       # 连接等待时间 (ms)
                shutdown-timeout: 1000   # 关闭超时时间 (ms)`


# 可选：Bucket4j 配置
bucket4j:
    enabled: true
    filters:
        - cache-name: rate-limit-bucket
            # 每分钟允许10次请求
          rate-limits:
              - bandwidths:
                    - capacity: 10
                      time: 1
                      unit: minutes